name: Linter

on: [push, pull_request]

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v1
    # Install Node.js
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        
    - name: npm install, and lint
      run: |
        npm ci
        npm lint
      env:
        CI: true
